-- Behavior for bhvAlphaBooKey and bhvBetaBooKey (Luigi Keys)

--static void write_ext_save(s32 fileIndex) {
--    if (INVALID_FILE_INDEX(fileIndex)) { return; }
--    
--    char filename[SYS_MAX_PATH] = { 0 };
--    if (snprintf(filename, sizeof(filename), EXT_SAVE_FILENAME_FORMAT, fs_writepath, fileIndex) < 0) {
--        return;
--    }
--    
--    FILE *file = fopen(filename, "wt");
--    if (file == NULL) {
--        return;
--    }
--    
--    fprintf(file, "# Render96DX Extended Save Data\n");
--    fprintf(file, "# This file stores luigi keys and wario coins\n\n");
--    
--    fprintf(file, "[keys]\n");
--    for (s32 i = 0; i < NUM_KEYS; i++) {
--        fprintf(file, "key_%d = %d\n", i, sExtSaveKeys[fileIndex][i] ? 1 : 0);
--    }
--    
--    fprintf(file, "\n[wario_coins]\n");
--    for (s32 i = 0; i < NUM_WARIO_COINS; i++) {
--        fprintf(file, "coin_%d = %d\n", i, sExtSaveWarioCoins[fileIndex][i] ? 1 : 0);
--    }
--    
--    fclose(file);
--}



--/**
-- * Renders the amount of Luigi keys collected.
-- */
--void render_hud_keys(void) {
--    if (gHudDisplay.keys > 0 && gHudDisplay.keys < 10) {
--        gSPDisplayList(gDisplayListHead++, dl_hud_img_begin);
--        render_hud_tex_lut(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(22), 35, (u8 *)texture_hud_boo_key);
--        gSPDisplayList(gDisplayListHead++, dl_hud_img_end);
--        print_text(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(38), HUD_TOP_Y - 20, "*"); // 'X' glyph
--        print_text_fmt_int(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(54), HUD_TOP_Y - 20, "%d", gHudDisplay.keys);
--    }
--}
--
--/**
-- * Renders the amount of Wario coins collected.
-- */
--void render_hud_wario_coins(void) {
--    if (gHudDisplay.wario_coins > 0 && gHudDisplay.wario_coins < 6) {
--        gSPDisplayList(gDisplayListHead++, dl_hud_img_begin);
--        render_hud_tex_lut(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(22), 55, (u8 *)texture_hud_wario_coin);
--        gSPDisplayList(gDisplayListHead++, dl_hud_img_end);
--        print_text(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(38), HUD_TOP_Y - 40, "*"); // 'X' glyph
--        print_text_fmt_int(GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(54), HUD_TOP_Y - 40, "%d", gHudDisplay.wario_coins);
--    }
--}

