extern const GeoLayout inner_workings_area_1_geo[];
extern const GeoLayout inner_workings_area_1[];
extern const Collision inner_workings_area_1_collision[];
extern const MacroObject inner_workings_area_1_macro_objs[];
extern Lights1 inner_workings_dl_Brick_Wall_lights;
extern Lights1 inner_workings_dl_Grate_Outline_lights;
extern Lights1 inner_workings_dl_Grate_lights;
extern Lights1 inner_workings_dl_Brick_Wall_001_lights;
extern u8 inner_workings_dl_texhd_rgba32[];
extern u8 inner_workings_dl_downscaledgrateoutline_rgba32[];
extern u8 inner_workings_dl_downscaledgrate_rgba32[];
extern u8 inner_workings_dl_floorhd_rgba32[];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_cull[8];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_0[428];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_0[];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_1[157];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_1[];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_2[151];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_2[];
extern Vtx inner_workings_dl_Level_mesh_layer_5_vtx_cull[8];
extern Vtx inner_workings_dl_Level_mesh_layer_5_vtx_0[40];
extern Gfx inner_workings_dl_Level_mesh_layer_5_tri_0[];
extern Gfx mat_inner_workings_dl_Brick_Wall[];
extern Gfx mat_revert_inner_workings_dl_Brick_Wall[];
extern Gfx mat_inner_workings_dl_Grate_Outline[];
extern Gfx mat_revert_inner_workings_dl_Grate_Outline[];
extern Gfx mat_inner_workings_dl_Grate[];
extern Gfx mat_revert_inner_workings_dl_Grate[];
extern Gfx mat_inner_workings_dl_Brick_Wall_001[];
extern Gfx mat_revert_inner_workings_dl_Brick_Wall_001[];
extern Gfx inner_workings_dl_Level_mesh_layer_1[];
extern Gfx inner_workings_dl_Level_mesh_layer_5[];
extern Gfx inner_workings_dl_material_revert_render_settings[];
