#include "levels/inner_workings/texture_include.inc.c"
#include "levels/inner_workings/area_1/collision.inc.c"
#include "levels/inner_workings/area_1/macro.inc.c"
#include "levels/inner_workings/area_1/spline.inc.c"
#include "levels/inner_workings/model.inc.c"
